/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/routes': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Получить список маршрутов */
    get: operations['getRoutes'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/routes/{route}/geometry': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Получить трассу маршрута (остановки с координатами) */
    get: operations['getRouteGeometry'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/forecast': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Получить прогноз (день — по часам, месяц — по дням)
     * @description Из этого метода фронтенд строит таблицы «маршруты × часы», «дни × часы» и окраску карты.
     */
    get: operations['getForecast'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/actuals': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Получить факт пассажиропотока (январь–октябрь 2025) */
    get: operations['getActuals'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/factors': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Получить факторы дня и вклад факторов в прогноз */
    get: operations['getFactors'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/export': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Выгрузить прогноз (CSV, XLSX, формат сабмита)
     * @description CSV — разделитель «;», UTF-8, числа без разделителей разрядов.
     *     submission — ровно route;date;hour;prediction, как test_submission.csv (только horizon=day).
     */
    get: operations['exportForecast'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/validations': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Принять валидации (потоковый приём, до 5000 записей) */
    post: operations['ingestValidations'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Проверить работоспособность */
    get: operations['getHealth'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/model/quality': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Получить качество модели (MAE нашей и базовой модели) */
    get: operations['getModelQuality'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/decisions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Получить список решений
     * @description Перед выдачей просроченные решения (awaiting, updated с истёкшим deadline_at) переводятся в expired.
     */
    get: operations['getDecisions'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/decisions/{decision_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Изменить статус решения (принять, отклонить, исполнено)
     * @description Допустимые переходы: awaiting, updated → accepted, rejected; accepted → executed, not_executed.
     *     При принятии одного варианта остальные варианты этого решения переводятся в closed.
     */
    patch: operations['updateDecisionStatus'];
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * @default day
     * @enum {string}
     */
    Horizon: 'day' | 'month';
    Error: {
      /** @enum {string} */
      code:
        | 'VALIDATION_ERROR'
        | 'UNAUTHORIZED'
        | 'FORBIDDEN'
        | 'ROUTE_NOT_FOUND'
        | 'GEOMETRY_NOT_FOUND'
        | 'FORECAST_NOT_FOUND'
        | 'ACTUALS_NOT_FOUND'
        | 'DATE_NOT_IN_CALENDAR'
        | 'DECISION_NOT_FOUND'
        | 'MODEL_VERSION_NOT_FOUND'
        | 'INVALID_STATUS_TRANSITION'
        | 'DECISION_EXPIRED'
        | 'INTERNAL_ERROR'
        | 'FORECAST_NOT_READY';
      /** @description Текст ошибки для пользователя */
      message: string;
      details?: {
        field: string;
        message: string;
      }[];
    };
    Route: {
      /**
       * @description route.route
       * @example 1
       */
      route: number;
      /**
       * @description route.route_long_name
       * @example Чертаново Южное - Москворецкий рынок
       */
      route_long_name?: string | null;
      /**
       * @description route.depot_id
       * @example 133
       */
      depot_id?: number | null;
      /**
       * @description depot.depot_name
       * @example Трамвайное управление
       */
      depot_name?: string | null;
      /**
       * Format: date
       * @description route.date_start
       */
      date_start?: string | null;
      /** @description route.is_new — новый маршрут без истории */
      is_new: boolean;
      /** @description route.has_geometry — есть координаты для карты */
      has_geometry: boolean;
    };
    RouteList: {
      items: components['schemas']['Route'][];
      total: number;
    };
    Stop: {
      /**
       * @description route_stop.stop_sequence
       * @example 1
       */
      stop_sequence: number;
      /**
       * @description stop.stop_id
       * @example 2594
       */
      stop_id: number;
      /**
       * @description stop.stop_name
       * @example Чертаново Южное
       */
      stop_name: string;
      /**
       * @description stop.stop_lat
       * @example 55.59468
       */
      stop_lat: number;
      /**
       * @description stop.stop_lon
       * @example 37.590884
       */
      stop_lon: number;
    };
    RouteGeometry: {
      route: number;
      route_long_name?: string | null;
      directions: {
        /** @enum {integer} */
        direction_id: 0 | 1;
        stops: components['schemas']['Stop'][];
      }[];
    };
    ForecastItem: {
      /**
       * @description forecast.route
       * @example 17
       */
      route: number;
      /**
       * Format: date
       * @description forecast.date
       * @example 2025-11-14
       */
      date: string;
      /**
       * @description forecast.hour; null для month
       * @example 8
       */
      hour?: number | null;
      /**
       * @description forecast.prediction — пассажиров за час (day) или за день (month)
       * @example 1859
       */
      prediction: number;
      /**
       * @description forecast.lower
       * @example 1690
       */
      lower: number;
      /**
       * @description forecast.upper
       * @example 2030
       */
      upper: number;
      /**
       * @description forecast.trams_on_line
       * @example 14
       */
      trams_on_line?: number | null;
      /**
       * @description prediction / trams_on_line
       * @example 132.8
       */
      passengers_per_tram?: number | null;
      /** @description forecast.is_analog — прогноз по аналогам */
      is_analog: boolean;
    };
    ForecastResponse: {
      /**
       * @description model_version.version_name
       * @example lgbm-v3
       */
      model_version: string;
      horizon: components['schemas']['Horizon'];
      items: components['schemas']['ForecastItem'][];
      /**
       * Format: date-time
       * @description forecast.created_at
       */
      generated_at: string;
    };
    ActualItem: {
      /** @description boardings_hourly.route */
      route: number;
      /**
       * Format: date
       * @description boardings_hourly.date
       */
      date: string;
      /** @description boardings_hourly.hour; null для day */
      hour?: number | null;
      /**
       * @description boardings_hourly.boardings
       * @example 581
       */
      boardings: number;
      /** @description boardings_hourly.trams_on_line (только hour) */
      trams_on_line?: number | null;
    };
    ActualsResponse: {
      /** @enum {string} */
      granularity: 'hour' | 'day';
      items: components['schemas']['ActualItem'][];
    };
    FactorsResponse: {
      /** Format: date */
      date: string;
      /** @description calendar_day.day_of_week */
      day_of_week: number;
      /**
       * @description calendar_day.day_type
       * @enum {string}
       */
      day_type: 'working' | 'weekend' | 'holiday' | 'shortened';
      holiday_name?: string | null;
      is_school_holiday: boolean;
      special_day_name?: string | null;
      /** @description Погода за день без утечки — прогноз, выпущенный до даты, или климатическая норма */
      weather?: {
        /** @enum {string} */
        data_kind?: 'forecast' | 'climate_norm';
        temperature_min?: number;
        temperature_max?: number;
        precipitation_mm?: number;
        snowfall_cm?: number;
      } | null;
      events: {
        event_id: number;
        /** @enum {string} */
        event_type: 'match' | 'concert' | 'exhibition' | 'metro_closure' | 'road_closure' | 'other';
        /** @example Матч ЦСКА */
        event_name: string;
        /** Format: date-time */
        start_at: string;
        routes: number[];
      }[];
      /** @description Только если передан route */
      contributions?: {
        /** @example peak_hour */
        factor_code: string;
        /** @example Час пик */
        factor_name: string;
        /** @example 38 */
        effect_pct: number;
      }[];
    };
    ValidationRecord: {
      tran_no: number;
      device_no: number;
      /** Format: date-time */
      tran_date_time: string;
      /** Format: date-time */
      begin_date_time?: string | null;
      crd_hashcode: string;
      /** @description 1 — успешно */
      validation_result: number;
      tran_type_id?: number | null;
      good_type?: string | null;
      pass_route?: string | null;
      route: number;
      bus_exit_no?: number | null;
      garage_number?: number | null;
    };
    ValidationBatch: {
      items: components['schemas']['ValidationRecord'][];
    };
    IngestResult: {
      accepted: number;
      rejected: number;
      errors: {
        /** @description Номер записи в пакете (с 0) */
        index: number;
        field: string;
        message: string;
      }[];
    };
    Health: {
      /** @enum {string} */
      status: 'UP' | 'DEGRADED' | 'DOWN';
      /** @enum {string} */
      db: 'UP' | 'DOWN';
      active_model_version?: string | null;
      /** Format: date-time */
      forecast_generated_at?: string | null;
    };
    QualityValues: {
      /**
       * @description model_quality.model_mae
       * @example 38
       */
      model_mae: number;
      /**
       * @description model_quality.baseline_mae
       * @example 71
       */
      baseline_mae: number;
      /** @description (baseline_mae − model_mae) / baseline_mae × 100 */
      improvement_pct?: number | null;
    };
    ModelQuality: {
      model_version: string;
      horizon: components['schemas']['Horizon'];
      /** Format: date */
      eval_date_from: string;
      /** Format: date */
      eval_date_to: string;
      overall: components['schemas']['QualityValues'];
      by_route: (components['schemas']['QualityValues'] & {
        route: number;
        /**
         * @description analogs — проверка с исключением
         * @enum {string}
         */
        method: 'model' | 'analogs';
      })[];
    };
    /** @enum {string} */
    DecisionStatusCode:
      | 'generated'
      | 'awaiting'
      | 'updated'
      | 'accepted'
      | 'rejected'
      | 'expired'
      | 'executed'
      | 'not_executed'
      | 'closed';
    Decision: {
      decision_id: number;
      /** @description Основное решение для альтернативы */
      parent_decision_id?: number | null;
      /** @enum {string} */
      decision_type: 'transfer' | 'reserve';
      /** @description Маршрут с превышением нормы */
      route: number;
      /** @description Маршрут-донор; null для reserve */
      donor_route?: number | null;
      /** Format: date */
      date: string;
      hour_from: number;
      hour_to: number;
      trams_delta: number;
      /** @example 150 */
      norm: number;
      /** @example 167 */
      load_before: number;
      /** @example 146 */
      load_after: number;
      /** @example 64 */
      donor_load_before?: number | null;
      /** @example 80 */
      donor_load_after?: number | null;
      /**
       * @description (load_before / norm − 1) × 100
       * @example 11
       */
      excess_pct: number;
      same_depot: boolean;
      /** Format: date-time */
      deadline_at: string;
      status_code: components['schemas']['DecisionStatusCode'];
      /** @example Ожидает решения */
      status_name: string;
      /** Format: date-time */
      created_at: string;
    };
    DecisionList: {
      items: components['schemas']['Decision'][];
      total: number;
    };
    DecisionStatusUpdate: {
      /** @enum {string} */
      status_code: 'accepted' | 'rejected' | 'executed' | 'not_executed';
      /** @description Обязательна для rejected и not_executed */
      reason?: string;
    };
    DecisionStatusResult: {
      decision_id: number;
      status_code: components['schemas']['DecisionStatusCode'];
      status_name: string;
      /** Format: date-time */
      changed_at: string;
      changed_by: string;
      reason?: string | null;
    };
  };
  responses: {
    /** @description VALIDATION_ERROR — некорректные параметры запроса */
    BadRequest: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        /**
         * @example {
         *       "code": "VALIDATION_ERROR",
         *       "message": "Некорректные параметры запроса",
         *       "details": [
         *         {
         *           "field": "date_from",
         *           "message": "Дата должна быть в формате YYYY-MM-DD"
         *         }
         *       ]
         *     }
         */
        'application/json': components['schemas']['Error'];
      };
    };
    /** @description UNAUTHORIZED — токен не передан или недействителен */
    Unauthorized: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        /**
         * @example {
         *       "code": "UNAUTHORIZED",
         *       "message": "Требуется авторизация"
         *     }
         */
        'application/json': components['schemas']['Error'];
      };
    };
    /** @description FORBIDDEN — нет роли для операции */
    Forbidden: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        /**
         * @example {
         *       "code": "FORBIDDEN",
         *       "message": "Недостаточно прав для выполнения операции"
         *     }
         */
        'application/json': components['schemas']['Error'];
      };
    };
    /** @description ROUTE_NOT_FOUND, GEOMETRY_NOT_FOUND, FORECAST_NOT_FOUND, ACTUALS_NOT_FOUND, DATE_NOT_IN_CALENDAR, DECISION_NOT_FOUND, MODEL_VERSION_NOT_FOUND */
    NotFound: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        /**
         * @example {
         *       "code": "ROUTE_NOT_FOUND",
         *       "message": "Маршрут 99 не найден"
         *     }
         */
        'application/json': components['schemas']['Error'];
      };
    };
    /** @description INVALID_STATUS_TRANSITION, DECISION_EXPIRED */
    Conflict: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        /**
         * @example {
         *       "code": "INVALID_STATUS_TRANSITION",
         *       "message": "Нельзя перевести решение из статуса rejected в accepted"
         *     }
         */
        'application/json': components['schemas']['Error'];
      };
    };
    /** @description INTERNAL_ERROR — внутренняя ошибка сервиса */
    InternalError: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        /**
         * @example {
         *       "code": "INTERNAL_ERROR",
         *       "message": "Внутренняя ошибка. Повторите запрос позже"
         *     }
         */
        'application/json': components['schemas']['Error'];
      };
    };
    /** @description FORECAST_NOT_READY — нет активной версии модели или БД недоступна */
    NotReady: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        /**
         * @example {
         *       "code": "FORECAST_NOT_READY",
         *       "message": "Прогноз ещё не рассчитан. Повторите позже"
         *     }
         */
        'application/json': components['schemas']['Error'];
      };
    };
  };
  parameters: {
    /** @description Номер маршрута */
    RoutePath: number;
    /** @description Номер маршрута; можно несколько (route=1&route=7). Если не передан — все */
    RouteQuery: number[];
    DateFrom: string;
    Horizon: components['schemas']['Horizon'];
    HorizonRequired: components['schemas']['Horizon'];
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type Horizon = components['schemas']['Horizon'];
export type Error = components['schemas']['Error'];
export type Route = components['schemas']['Route'];
export type RouteList = components['schemas']['RouteList'];
export type Stop = components['schemas']['Stop'];
export type RouteGeometry = components['schemas']['RouteGeometry'];
export type ForecastItem = components['schemas']['ForecastItem'];
export type ForecastResponse = components['schemas']['ForecastResponse'];
export type ActualItem = components['schemas']['ActualItem'];
export type ActualsResponse = components['schemas']['ActualsResponse'];
export type FactorsResponse = components['schemas']['FactorsResponse'];
export type ValidationRecord = components['schemas']['ValidationRecord'];
export type ValidationBatch = components['schemas']['ValidationBatch'];
export type IngestResult = components['schemas']['IngestResult'];
export type Health = components['schemas']['Health'];
export type QualityValues = components['schemas']['QualityValues'];
export type ModelQuality = components['schemas']['ModelQuality'];
export type DecisionStatusCode = components['schemas']['DecisionStatusCode'];
export type Decision = components['schemas']['Decision'];
export type DecisionList = components['schemas']['DecisionList'];
export type DecisionStatusUpdate = components['schemas']['DecisionStatusUpdate'];
export type DecisionStatusResult = components['schemas']['DecisionStatusResult'];
export type ResponseBadRequest = components['responses']['BadRequest'];
export type ResponseUnauthorized = components['responses']['Unauthorized'];
export type ResponseForbidden = components['responses']['Forbidden'];
export type ResponseNotFound = components['responses']['NotFound'];
export type ResponseConflict = components['responses']['Conflict'];
export type ResponseInternalError = components['responses']['InternalError'];
export type ResponseNotReady = components['responses']['NotReady'];
export type ParameterRoutePath = components['parameters']['RoutePath'];
export type ParameterRouteQuery = components['parameters']['RouteQuery'];
export type ParameterDateFrom = components['parameters']['DateFrom'];
export type ParameterHorizon = components['parameters']['Horizon'];
export type ParameterHorizonRequired = components['parameters']['HorizonRequired'];
export type $defs = Record<string, never>;
export interface operations {
  getRoutes: {
    parameters: {
      query?: {
        /** @description true — только новые маршруты без истории, false — только с историей */
        is_new?: boolean;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Список маршрутов */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RouteList'];
        };
      };
      400: components['responses']['BadRequest'];
      500: components['responses']['InternalError'];
    };
  };
  getRouteGeometry: {
    parameters: {
      query?: {
        /** @description Направление 0 или 1; если не передано — оба */
        direction_id?: 0 | 1;
      };
      header?: never;
      path: {
        /** @description Номер маршрута */
        route: components['parameters']['RoutePath'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Остановки маршрута по направлениям */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RouteGeometry'];
        };
      };
      400: components['responses']['BadRequest'];
      404: components['responses']['NotFound'];
      500: components['responses']['InternalError'];
    };
  };
  getForecast: {
    parameters: {
      query: {
        /** @description Номер маршрута; можно несколько (route=1&route=7). Если не передан — все */
        route?: components['parameters']['RouteQuery'];
        date_from: components['parameters']['DateFrom'];
        /** @description Конец периода; по умолчанию = date_from; период не больше 62 дней */
        date_to?: string;
        horizon?: components['parameters']['Horizon'];
        /** @description Начальный час (только для day), по умолчанию 0 */
        hour_from?: number;
        /** @description Конечный час (только для day), по умолчанию 23 */
        hour_to?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Прогноз */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ForecastResponse'];
        };
      };
      400: components['responses']['BadRequest'];
      404: components['responses']['NotFound'];
      500: components['responses']['InternalError'];
      503: components['responses']['NotReady'];
    };
  };
  getActuals: {
    parameters: {
      query: {
        /** @description Номер маршрута; можно несколько (route=1&route=7). Если не передан — все */
        route?: components['parameters']['RouteQuery'];
        date_from: components['parameters']['DateFrom'];
        /** @description Конец периода; не больше 92 дней от начала */
        date_to: string;
        granularity?: 'hour' | 'day';
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Фактические значения */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ActualsResponse'];
        };
      };
      400: components['responses']['BadRequest'];
      404: components['responses']['NotFound'];
      500: components['responses']['InternalError'];
    };
  };
  getFactors: {
    parameters: {
      query: {
        date: string;
        /** @description Если передан — добавляются вклад факторов и события рядом с маршрутом */
        route?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Факторы дня */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FactorsResponse'];
        };
      };
      400: components['responses']['BadRequest'];
      404: components['responses']['NotFound'];
      500: components['responses']['InternalError'];
    };
  };
  exportForecast: {
    parameters: {
      query: {
        format: 'csv' | 'xlsx' | 'submission';
        /** @description Номер маршрута; можно несколько (route=1&route=7). Если не передан — все */
        route?: components['parameters']['RouteQuery'];
        date_from: components['parameters']['DateFrom'];
        date_to: string;
        horizon?: components['parameters']['Horizon'];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Файл с прогнозом */
      200: {
        headers: {
          /** @example attachment; filename=forecast_2025-11-01_2025-12-31.csv */
          'Content-Disposition'?: string;
          [name: string]: unknown;
        };
        content: {
          /**
           * @example route;date;hour;prediction
           *     1;2025-11-01;5;142
           *     1;2025-11-01;6;566
           */
          'text/csv': string;
          'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet': string;
        };
      };
      400: components['responses']['BadRequest'];
      404: components['responses']['NotFound'];
      500: components['responses']['InternalError'];
      503: components['responses']['NotReady'];
    };
  };
  ingestValidations: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ValidationBatch'];
      };
    };
    responses: {
      /** @description Результат приёма (некорректные записи не сохраняются и перечисляются в errors) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['IngestResult'];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      500: components['responses']['InternalError'];
    };
  };
  getHealth: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Сервис работает */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Health'];
        };
      };
      /** @description БД недоступна */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Health'];
        };
      };
    };
  };
  getModelQuality: {
    parameters: {
      query: {
        horizon: components['parameters']['HorizonRequired'];
        /** @description Версия модели; по умолчанию активная */
        model_version?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Качество модели */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ModelQuality'];
        };
      };
      400: components['responses']['BadRequest'];
      404: components['responses']['NotFound'];
      500: components['responses']['InternalError'];
      503: components['responses']['NotReady'];
    };
  };
  getDecisions: {
    parameters: {
      query?: {
        status?: components['schemas']['DecisionStatusCode'][];
        date?: string;
        route?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Список решений */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DecisionList'];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      500: components['responses']['InternalError'];
    };
  };
  updateDecisionStatus: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        decision_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        /**
         * @example {
         *       "status_code": "rejected",
         *       "reason": "Нет резерва в депо"
         *     }
         */
        'application/json': components['schemas']['DecisionStatusUpdate'];
      };
    };
    responses: {
      /** @description Статус изменён */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DecisionStatusResult'];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
      409: components['responses']['Conflict'];
      500: components['responses']['InternalError'];
    };
  };
}
